language: node_js
sudo: true
node_js: 6
script:
- npm test
env:
  global:
  - CF_APP=visual-recognition-demo
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=WatsonPlatformServices
  - CF_SPACE=demos
  - VISUAL_RECOGNITION_API_KEY="bogus key to let server spin up for offline tests"
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script:
    - cf-blue-green-travis
  on:
    branch: master
    repo: watson-developer-cloud/visual-recognition-nodejs
  skip_cleanup: true
notifications:
  email: false
